### PR TITLE
Offline mode 

### LINKED ISSUE #210: In the case where the authentication fails due to no internet connection, launch the MainActivity in offline mode.

### PR DESCRIPTION
**Pull request by CorentinBT**
Closes #210, #211, #212.

### CODE REVIEW

**Review by MartinBeaussart — APPROVED** [review]

File: app/src/main/java/ch/epfl/sdp/offline/ConnectivityService.java [hunk 1]
```diff
@@ -0,0 +1,8 @@
+package ch.epfl.sdp.offline;
+
+import android.content.Context;
+
+public interface ConnectivityService {
+
+    boolean isNetworkAvailable(Context context);
```
Comment (mjmorale) [inline app/src/main/java/ch/epfl/sdp/offline/ConnectivityService.java:16]: Doc

**Review by mjmorale — CHANGES_REQUESTED** [review]

**Review by mjmorale — APPROVED** [review]
